require: rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/**/*"
    - "vendor/**/*"
    - "app/views/**/*"
    - "config.ru"
    - "Rakefile"

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'spec/support/helpers/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/support/helpers/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/**/*'
