defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:

production:
  url: <%= ENV["DATABASE_URL"] %>

test:
  database: money_manager_test
  <<: *defaults

development:
  database: money_manager_development
  <<: *defaults
