defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *defaults

test:
  database: money_manager_test
  <<: *defaults

development:
  database: money_manager_development
  <<: *defaults
